### PR TITLE
[#213] Use file cache store for embedded cache

### LINKED ISSUE #213: Configure file cache store for embedded Command Router cache
In case an embedded cache is used for the Hono Command Router component, file persistence should be enabled for the cache so that command subscriptions will be restored when the Hono Command Router component is restarted.

### PR DESCRIPTION
**Pull request by calohmn**
Also update to Hono 1.6.1.

This fixes #213 and applies the fix for https://github.com/eclipse/hono/issues/2576.

### CODE REVIEW

**Comment by calohmn** [comment]
CI run fails because "hono-adapter-mqtt-vertx:1.6.1" isn't available yet on Dockerhub.

**Review by sophokles73 — APPROVED** [review]
LGTM

maybe it is worth mentioning in the readme that the Command Router service requires a PV now?

**Comment by calohmn** [comment]
Yes, I've adapted the README accordingly.

**Review by sophokles73 — APPROVED** [review]
LGTM

**Pull request merged**
