### PR TITLE
Upon restart, file base device registry configuration is overwritten

### PR DESCRIPTION
**Pull request by BobClaerhout**
Somehow, this slipped back in: https://github.com/eclipse/hono/issues/1007
Signed-off-by: Bob Claerhout <claerhout.bob@gmail.com>

### CODE REVIEW

**Comment by ctron** [comment]
@BobClaerhout could you rebase on master, that should fix the CI issues

**Comment by BobClaerhout** [comment]
> @BobClaerhout could you rebase on master, that should fix the CI issues

Oops, sorry. Should have known it from the first time.
Done

**Comment by BobClaerhout** [comment]
No changes anymore from master to the current branch.

**Comment by sophokles73** [comment]
@BobClaerhout this did not *slip back in* but has been fixed again so that the copy commands can actually be run by the busybox image. You can try for yourself:
```
 $ docker run -it --rm busybox /bin/sh -c 'cp -n /etc/hostname /etc/hostname.bak'
cp: invalid option -- n
BusyBox v1.31.1 (2020-03-09 21:47:38 UTC) multi-call binary.

Usage: cp [OPTIONS] SOURCE... DEST

Copy SOURCE(s) to DEST

	-a	Same as -dpR
	-R,-r	Recurse
	-d,-P	Preserve symlinks (default if -R)
	-L	Follow all symlinks
	-H	Follow symlinks on command line
	-p	Preserve file attributes if possible
	-f	Overwrite
	-i	Prompt before overwrite
	-l,-s	Create (sym)links
	-T	Treat DEST as a normal file
	-u	Copy only newer files
```
The included version of *cp* simply doesn't support the `-n` option ...

**Comment by BobClaerhout** [comment]
Ok, but the problem still exists if we keep the `cp -u`. The data gets overwritten upon each run of the busybox.

**Comment by BobClaerhout** [comment]
Updated with a check in bash

**Comment by ctron** [comment]
Ok, the CI is happy again.

**Pull request merged**
