### PR TITLE
Hawkbit: Use networking.k8s.io/v1 for Ingress if available

### PR DESCRIPTION
**Pull request by PSanetra**
This PR adds support for the v1 Ingress resource which is necessary for a deployment to Kubernetes 1.22.

### CODE REVIEW

**Comment by ctron** [comment]
@laverman @kaizimmerm could any of you take a look at this

**Comment by zidex** [comment]
helm-chart is not supported anymore?

**Comment by bulmust** [comment]
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Comment by rondegroot** [comment]
I'm also waiting for this. Please merge this PR to keep supporting the helm-chart.

**Comment by bulmust** [comment]
> I'm also waiting for this. Please merge this PR to keep supporting the helm-chart.

I give up and maintain it by myself.

By the way, you can add storage class under [this line](https://github.com/eclipse/packages/blob/f79acefebad8a84cb5a3decc014589ea9b4974b2/charts/hawkbit/templates/pvc.yaml#L18): `storageClassName: {{ .Values.fileStorage.storageClass }}` (Be careful to indent)

**Comment by paltaa** [comment]
Is this maintained? @bulmust do you have your own version public? Need to add custom serviceAccounts

**Comment by bulmust** [comment]
> Is this maintained? @bulmust do you have your own version public? Need to add custom serviceAccounts

I do not publish my own helm chart to anywhere. By the way, this helm chart has a lot of problems like absence of serviceAccounts, storageClass etc, so as I understand this repo does not maintained anymore. You should also consider [hawkbit microservice mode](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/docker/docker-compose-micro-services-mysql-with-simple-ui.yml) which is not compatible with this helm chart.

**Comment by paltaa** [comment]
Alright, thanks for the response! @bulmust, will just copy it and create our own version

**Comment by calohmn** [comment]
Sorry this didn't get attention for so long. @strailov @avgustinmm Any comments on this? It looks good to me.
I guess it could make sense to merge this before the hawkbit 0.5.0 update [PR](https://github.com/eclipse/packages/pull/549).

@PSanetra In order to be able to merge this, the chart (patch) version needs to be updated in the [Chart.yaml](https://github.com/eclipse/packages/blob/f79acefebad8a84cb5a3decc014589ea9b4974b2/charts/hawkbit/Chart.yaml#L13). This requires a prior git rebase, so that the change is based on the current chart version.
Could you do that still? Or, if you don't mind, I could make that change and push to your PR branch (if that was enabled on PR creation).

**Review by calohmn — APPROVED** [review]

**Comment by calohmn** [comment]
Commit merged via #550.

**Pull request closed without merging**
