### PR TITLE
WIP: Testing CI by doing simple change provoking CI pipeline to start

### PR DESCRIPTION
**Pull request by thjaeckle**
Do not merge PR

### CODE REVIEW

**Comment by monotek** [comment]
Hint: You could use the Github WIP app to prevent merging: https://github.com/apps/wip

**Comment by monotek** [comment]
8m 8s :) Not bad for testing it in 7 Kubernetes versions :sunglasses:

**Comment by thjaeckle** [comment]
thx @monotek 
The CI checks passed successfully, looking great 👍 

What I learned: The Chart version must always be increased, even when doing "-snapshot" suffix (e.g. adding ".1".

o you have any additional thoughts? :)

**Comment by monotek** [comment]
Yes, imho version has to be bumped evenf if only the readme is changed to prevent binary different Helm tar.gz archives with the same version number.

Nothing more to add for now from my side.

I have to talk to @axdotl when we'll move the charts from our repo to this one but he is in vacation already. But maybe he's answering anyway ;-)

**Comment by thjaeckle** [comment]
Discarding - the PR was only for testing the CI.

**Pull request closed without merging**
