### PR TITLE
adds documentation for local Kubernetes deployment based on MicroK8s

### PR DESCRIPTION
**Pull request by eriksven**
With this PR we propose to extend the documentation of the prerequisites to the case were one wants to run Kubernetes locally. In the described approach we use MicroK8s. Please note that @LuLeRoemer joined the efforts for this PR.

### CODE REVIEW

**Comment by ctron** [comment]
> Please note that @LuLeRoemer joined the efforts for this PR.

If that is the case, then please amend the commit, adding the co-author: https://www.eclipse.org/projects/handbook/#resources-commit

**Comment by eriksven** [comment]
Thank you for the hint. I updated the commit message.

**Comment by ctron** [comment]
So it looks like the ECA check tool did not catch that. I raised an issue with EMO and would kindly ask you to be patient until this is sorted out. Please ping me if this takes too long for you and we will find a solution.

**Comment by sophokles73** [comment]
@ctron is there still an issue with this PR or can it be merged now?

**Comment by eriksven** [comment]
@ctron did you get a feedback from the EMO? Is there a way in which we can support you to solve the ECA check tool issue?

**Review by ctron — APPROVED** [review]
All good.

**Review by calohmn — APPROVED** [review]

**Pull request merged**
