### PR TITLE
Use Quarkus based images by default

### PR DESCRIPTION
**Pull request by sophokles73**
The Deviec Connection CI profile has been adapted to use the Spring Boot
based images.

### CODE REVIEW

**Comment by calohmn** [comment]
@sophokles73 Can you rebase and update the chart version?

**Comment by sophokles73** [comment]
> Can you rebase and update the chart version?

Is there anything wrong with the version?

**Comment by calohmn** [comment]
The version is already at 1.9.12 via the just added commit a1238be27f383575aafa0a1b800ca9c206ab3f0d.

**Comment by sophokles73** [comment]
Ah, I see

**Review by calohmn — APPROVED** [review]
LGTM

**Pull request merged**
