### PR TITLE
Fix ditto nginx proxy_set_header spelling of X-Forwarded-User

### PR DESCRIPTION
**Pull request by mladBlum**

### CODE REVIEW

**Comment by mladBlum** [comment]
chart version will be bumped after merge of https://github.com/eclipse/packages/pull/350

**Comment by thjaeckle** [comment]
While you are at it, updating the chart version, could you please also update the Ditto version from 2.3.0 to 2.3.2?

**Comment by mladBlum** [comment]
> While you are at it, updating the chart version, could you please also update the Ditto version from 2.3.0 to 2.3.2?

done.

**Review by thjaeckle — APPROVED** [review]
Good catch - I did not notice that typo yet.
Thx 👍

**Pull request merged**
