### PR TITLE
Fixed typo in README.md

### PR DESCRIPTION
**Pull request by patrickse**
Fixed typo in README.md

relm -> helm

Signed-off-by: Patrick Sernetz <patrick@sernetz.com>

### CODE REVIEW

**Comment by ctron** [comment]
@monotek The CI check failed because we need a new version. Technically I understand why … but is that really necessary?

**Comment by thjaeckle** [comment]
I would not bother in creating a new micro version - after all it's a bug fix.

**Comment by axdotl** [comment]
As the README is part of the Helm chart, a change on this also requires a new version. Because a change on the readme results in a new hash for the artifact (the packaged chart), this would cause trouble if the version remains the same but the digest has changed.

**Comment by patrickse** [comment]
Ok got it.. I will create a new version tomorrow as soon as I am in the office... sorry just wanted to fix this little typo, got no clue that this would lead to a new version 😉

**Pull request merged**
