### PR TITLE
[#372] Update hawkBit chart dependencies

### PR DESCRIPTION
**Pull request by calohmn**
This is for #372:
The hawkBit chart dependencies are updated to these versions:
- bitnami mysql chart 9.x (with mysql >= 8.0.29)
- bitnami rabbitmq chart 10.x (with rabbitmq >= 3.10.2)

### CODE REVIEW

**Review by ctron — APPROVED** [review]

**Comment by calohmn** [comment]
As discussed with @laverman some more tests are needed here to verify compatibility of hawkBit with mysql 8.0.

**Comment by calohmn** [comment]
I don't have the necessary hawkBit knowledge for this.
@laverman As discussed at the time, could you coordinate that these tests are done?

**Comment by strailov** [comment]
Everything seems fine on hawkBit side.

**Review by strailov — APPROVED** [review]

**Comment by calohmn** [comment]
Rebased, moved dependencies into `Chart.yaml` and changed bitnami repository location to the new default.

**Pull request merged**
