### PR TITLE
Hono: Set node port for external Kafka service.

### PR DESCRIPTION
**Pull request by b-abel**
This defines a node port for the external service of the example Kafka broker.

### CODE REVIEW

**Comment by calohmn** [comment]
@b-abel Can you rebase and update the chart version?

**Comment by calohmn** [comment]
@b-abel What is the motivation here?

**Comment by b-abel** [comment]
The idea is to define a fixed port number for the external Kafka service. Without this setting, Kubernetes picks port and there is no guarantee that it will always be the same number. This is only relevant if the service is of type "NodePort" (and not "LoadBalancer"). The other services in Hono define the ports as well.

**Comment by calohmn** [comment]
> The other services in Hono define the ports as well.

ok, right.

>  This is only relevant if the service is of type "NodePort" (and not "LoadBalancer"). 

It is also relevant for type "LoadBalancer", the LoadBalancer Type being an extension of the the NodePort type. "LoadBalancer" is used in the config changed here, anyway.

**Review by calohmn — APPROVED** [review]
LGTM

**Pull request merged**
